### ISSUE TITLE
Tidy up README

### ISSUE THREAD

**Issue by njtierney** [njtierney/conmat#35]
There's a lot of output in the README that could be cut down, and also the images and outputs keep changing on each render, when they should be fixed, so might need to fix the set.seed value?

**Comment by goldingn** [comment]
The readme images are still out of date (made with the version of the code prior to the offset bugfix). I'm not sure if that's because the images didn't update, or because the readme installed an older version of the package before running. Bu the schools one should look like this (note legend max 5, not 25):
<img width="502" alt="Screen Shot 2021-09-24 at 4 59 30 pm" src="https://user-images.githubusercontent.com/4450731/134648123-65e3bbdc-5465-413a-9aaf-631c10614ace.png">

**Comment by goldingn** [comment]
we should also switch away from Sydney as the example as it has a *weird* population distribution with very few kids

**Comment by njtierney** [comment]
Done in #78
